/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApkRouteImport } from './routes/apk'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as EmailVerifyRouteImport } from './routes/email.verify'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as UUsernameFollowingRouteImport } from './routes/u.$username.following'
import { Route as UUsernameFollowersRouteImport } from './routes/u.$username.followers'
import { Route as AuthenticatedFeedNewRouteImport } from './routes/_authenticated/feed.new'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard.wallet'
import { Route as AuthenticatedDashboardVaultRouteImport } from './routes/_authenticated/dashboard.vault'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardStatisticsRouteImport } from './routes/_authenticated/dashboard.statistics'
import { Route as AuthenticatedDashboardShopRouteImport } from './routes/_authenticated/dashboard.shop'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardReferralsRouteImport } from './routes/_authenticated/dashboard.referrals'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPremiumRouteImport } from './routes/_authenticated/dashboard.premium'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMyMatchesRouteImport } from './routes/_authenticated/dashboard.my-matches'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardMatchesRouteImport } from './routes/_authenticated/dashboard.matches'
import { Route as AuthenticatedDashboardFeedRouteImport } from './routes/_authenticated/dashboard.feed'
import { Route as AuthenticatedDashboardBlocksRouteImport } from './routes/_authenticated/dashboard.blocks'
import { Route as AdminAdminWithdrawalsRouteImport } from './routes/_admin/admin.withdrawals'
import { Route as AdminAdminWithdrawConfigRouteImport } from './routes/_admin/admin.withdraw-config'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminTwoFactorRouteImport } from './routes/_admin/admin.two-factor'
import { Route as AdminAdminTemplatesRouteImport } from './routes/_admin/admin.templates'
import { Route as AdminAdminSupportRouteImport } from './routes/_admin/admin.support'
import { Route as AdminAdminSmtpRouteImport } from './routes/_admin/admin.smtp'
import { Route as AdminAdminShopRouteImport } from './routes/_admin/admin.shop'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminSecurityRouteImport } from './routes/_admin/admin.security'
import { Route as AdminAdminResultsRouteImport } from './routes/_admin/admin.results'
import { Route as AdminAdminReferralConfigRouteImport } from './routes/_admin/admin.referral-config'
import { Route as AdminAdminPushRouteImport } from './routes/_admin/admin.push'
import { Route as AdminAdminPremiumRouteImport } from './routes/_admin/admin.premium'
import { Route as AdminAdminParticipantsRouteImport } from './routes/_admin/admin.participants'
import { Route as AdminAdminPagesRouteImport } from './routes/_admin/admin.pages'
import { Route as AdminAdminOnlineUsersRouteImport } from './routes/_admin/admin.online-users'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin/admin.notifications'
import { Route as AdminAdminMatchesRouteImport } from './routes/_admin/admin.matches'
import { Route as AdminAdminLoginHistoryRouteImport } from './routes/_admin/admin.login-history'
import { Route as AdminAdminGamesRouteImport } from './routes/_admin/admin.games'
import { Route as AdminAdminFeedRouteImport } from './routes/_admin/admin.feed'
import { Route as AdminAdminEmailSetupRouteImport } from './routes/_admin/admin.email-setup'
import { Route as AdminAdminDepositsRouteImport } from './routes/_admin/admin.deposits'
import { Route as AdminAdminCoinRatesRouteImport } from './routes/_admin/admin.coin-rates'
import { Route as AdminAdminChannelsRouteImport } from './routes/_admin/admin.channels'
import { Route as AdminAdminBusinessWalletsRouteImport } from './routes/_admin/admin.business-wallets'
import { Route as AdminAdminBalancesRouteImport } from './routes/_admin/admin.balances'
import { Route as AdminAdminBackupsRouteImport } from './routes/_admin/admin.backups'
import { Route as AdminAdminApkRouteImport } from './routes/_admin/admin.apk'
import { Route as AdminAdminAccountDeletionsRouteImport } from './routes/_admin/admin.account-deletions'
import { Route as AuthenticatedDashboardStoryNewRouteImport } from './routes/_authenticated/dashboard.story.new'
import { Route as AuthenticatedDashboardMessagesThreadIdRouteImport } from './routes/_authenticated/dashboard.messages.$threadId'
import { Route as AuthenticatedDashboardMatchesMatchIdRouteImport } from './routes/_authenticated/dashboard.matches.$matchId'
import { Route as AuthenticatedDashboardFeedPostIdRouteImport } from './routes/_authenticated/dashboard.feed.$postId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkRoute = ApkRouteImport.update({
  id: '/apk',
  path: '/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UUsernameFollowingRoute = UUsernameFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameFollowersRoute = UUsernameFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => UUsernameRoute,
} as any)
const AuthenticatedFeedNewRoute = AuthenticatedFeedNewRouteImport.update({
  id: '/feed/new',
  path: '/feed/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultRoute =
  AuthenticatedDashboardVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStatisticsRoute =
  AuthenticatedDashboardStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShopRoute =
  AuthenticatedDashboardShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReferralsRoute =
  AuthenticatedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPremiumRoute =
  AuthenticatedDashboardPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyMatchesRoute =
  AuthenticatedDashboardMyMatchesRouteImport.update({
    id: '/my-matches',
    path: '/my-matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatchesRoute =
  AuthenticatedDashboardMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFeedRoute =
  AuthenticatedDashboardFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBlocksRoute =
  AuthenticatedDashboardBlocksRouteImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminWithdrawalsRoute = AdminAdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminWithdrawConfigRoute =
  AdminAdminWithdrawConfigRouteImport.update({
    id: '/admin/withdraw-config',
    path: '/admin/withdraw-config',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminTwoFactorRoute = AdminAdminTwoFactorRouteImport.update({
  id: '/admin/two-factor',
  path: '/admin/two-factor',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminTemplatesRoute = AdminAdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSupportRoute = AdminAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSmtpRoute = AdminAdminSmtpRouteImport.update({
  id: '/admin/smtp',
  path: '/admin/smtp',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminShopRoute = AdminAdminShopRouteImport.update({
  id: '/admin/shop',
  path: '/admin/shop',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSecurityRoute = AdminAdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminResultsRoute = AdminAdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminReferralConfigRoute =
  AdminAdminReferralConfigRouteImport.update({
    id: '/admin/referral-config',
    path: '/admin/referral-config',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminPushRoute = AdminAdminPushRouteImport.update({
  id: '/admin/push',
  path: '/admin/push',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPremiumRoute = AdminAdminPremiumRouteImport.update({
  id: '/admin/premium',
  path: '/admin/premium',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminParticipantsRoute = AdminAdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagesRoute = AdminAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOnlineUsersRoute = AdminAdminOnlineUsersRouteImport.update({
  id: '/admin/online-users',
  path: '/admin/online-users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMatchesRoute = AdminAdminMatchesRouteImport.update({
  id: '/admin/matches',
  path: '/admin/matches',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLoginHistoryRoute = AdminAdminLoginHistoryRouteImport.update({
  id: '/admin/login-history',
  path: '/admin/login-history',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminGamesRoute = AdminAdminGamesRouteImport.update({
  id: '/admin/games',
  path: '/admin/games',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminFeedRoute = AdminAdminFeedRouteImport.update({
  id: '/admin/feed',
  path: '/admin/feed',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminEmailSetupRoute = AdminAdminEmailSetupRouteImport.update({
  id: '/admin/email-setup',
  path: '/admin/email-setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminDepositsRoute = AdminAdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCoinRatesRoute = AdminAdminCoinRatesRouteImport.update({
  id: '/admin/coin-rates',
  path: '/admin/coin-rates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminChannelsRoute = AdminAdminChannelsRouteImport.update({
  id: '/admin/channels',
  path: '/admin/channels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBusinessWalletsRoute =
  AdminAdminBusinessWalletsRouteImport.update({
    id: '/admin/business-wallets',
    path: '/admin/business-wallets',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminBalancesRoute = AdminAdminBalancesRouteImport.update({
  id: '/admin/balances',
  path: '/admin/balances',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBackupsRoute = AdminAdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminApkRoute = AdminAdminApkRouteImport.update({
  id: '/admin/apk',
  path: '/admin/apk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAccountDeletionsRoute =
  AdminAdminAccountDeletionsRouteImport.update({
    id: '/admin/account-deletions',
    path: '/admin/account-deletions',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AuthenticatedDashboardStoryNewRoute =
  AuthenticatedDashboardStoryNewRouteImport.update({
    id: '/story/new',
    path: '/story/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesThreadIdRoute =
  AuthenticatedDashboardMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedDashboardMessagesRoute,
  } as any)
const AuthenticatedDashboardMatchesMatchIdRoute =
  AuthenticatedDashboardMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedDashboardMatchesRoute,
  } as any)
const AuthenticatedDashboardFeedPostIdRoute =
  AuthenticatedDashboardFeedPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthenticatedDashboardFeedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/auth': typeof AuthRouteWithChildren
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/premium': typeof PremiumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/verify': typeof EmailVerifyRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/admin/account-deletions': typeof AdminAdminAccountDeletionsRoute
  '/admin/apk': typeof AdminAdminApkRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/balances': typeof AdminAdminBalancesRoute
  '/admin/business-wallets': typeof AdminAdminBusinessWalletsRoute
  '/admin/channels': typeof AdminAdminChannelsRoute
  '/admin/coin-rates': typeof AdminAdminCoinRatesRoute
  '/admin/deposits': typeof AdminAdminDepositsRoute
  '/admin/email-setup': typeof AdminAdminEmailSetupRoute
  '/admin/feed': typeof AdminAdminFeedRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/login-history': typeof AdminAdminLoginHistoryRoute
  '/admin/matches': typeof AdminAdminMatchesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/online-users': typeof AdminAdminOnlineUsersRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/participants': typeof AdminAdminParticipantsRoute
  '/admin/premium': typeof AdminAdminPremiumRoute
  '/admin/push': typeof AdminAdminPushRoute
  '/admin/referral-config': typeof AdminAdminReferralConfigRoute
  '/admin/results': typeof AdminAdminResultsRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shop': typeof AdminAdminShopRoute
  '/admin/smtp': typeof AdminAdminSmtpRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/two-factor': typeof AdminAdminTwoFactorRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdraw-config': typeof AdminAdminWithdrawConfigRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/dashboard/blocks': typeof AuthenticatedDashboardBlocksRoute
  '/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/dashboard/statistics': typeof AuthenticatedDashboardStatisticsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard/vault': typeof AuthenticatedDashboardVaultRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/feed/new': typeof AuthenticatedFeedNewRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
  '/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/dashboard/story/new': typeof AuthenticatedDashboardStoryNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/auth': typeof AuthRouteWithChildren
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/premium': typeof PremiumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/verify': typeof EmailVerifyRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/admin/account-deletions': typeof AdminAdminAccountDeletionsRoute
  '/admin/apk': typeof AdminAdminApkRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/balances': typeof AdminAdminBalancesRoute
  '/admin/business-wallets': typeof AdminAdminBusinessWalletsRoute
  '/admin/channels': typeof AdminAdminChannelsRoute
  '/admin/coin-rates': typeof AdminAdminCoinRatesRoute
  '/admin/deposits': typeof AdminAdminDepositsRoute
  '/admin/email-setup': typeof AdminAdminEmailSetupRoute
  '/admin/feed': typeof AdminAdminFeedRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/login-history': typeof AdminAdminLoginHistoryRoute
  '/admin/matches': typeof AdminAdminMatchesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/online-users': typeof AdminAdminOnlineUsersRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/participants': typeof AdminAdminParticipantsRoute
  '/admin/premium': typeof AdminAdminPremiumRoute
  '/admin/push': typeof AdminAdminPushRoute
  '/admin/referral-config': typeof AdminAdminReferralConfigRoute
  '/admin/results': typeof AdminAdminResultsRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shop': typeof AdminAdminShopRoute
  '/admin/smtp': typeof AdminAdminSmtpRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/two-factor': typeof AdminAdminTwoFactorRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdraw-config': typeof AdminAdminWithdrawConfigRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/dashboard/blocks': typeof AuthenticatedDashboardBlocksRoute
  '/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/dashboard/statistics': typeof AuthenticatedDashboardStatisticsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard/vault': typeof AuthenticatedDashboardVaultRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/feed/new': typeof AuthenticatedFeedNewRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
  '/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/dashboard/story/new': typeof AuthenticatedDashboardStoryNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/auth': typeof AuthRouteWithChildren
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/premium': typeof PremiumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/verify': typeof EmailVerifyRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/_admin/admin/account-deletions': typeof AdminAdminAccountDeletionsRoute
  '/_admin/admin/apk': typeof AdminAdminApkRoute
  '/_admin/admin/backups': typeof AdminAdminBackupsRoute
  '/_admin/admin/balances': typeof AdminAdminBalancesRoute
  '/_admin/admin/business-wallets': typeof AdminAdminBusinessWalletsRoute
  '/_admin/admin/channels': typeof AdminAdminChannelsRoute
  '/_admin/admin/coin-rates': typeof AdminAdminCoinRatesRoute
  '/_admin/admin/deposits': typeof AdminAdminDepositsRoute
  '/_admin/admin/email-setup': typeof AdminAdminEmailSetupRoute
  '/_admin/admin/feed': typeof AdminAdminFeedRoute
  '/_admin/admin/games': typeof AdminAdminGamesRoute
  '/_admin/admin/login-history': typeof AdminAdminLoginHistoryRoute
  '/_admin/admin/matches': typeof AdminAdminMatchesRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/online-users': typeof AdminAdminOnlineUsersRoute
  '/_admin/admin/pages': typeof AdminAdminPagesRoute
  '/_admin/admin/participants': typeof AdminAdminParticipantsRoute
  '/_admin/admin/premium': typeof AdminAdminPremiumRoute
  '/_admin/admin/push': typeof AdminAdminPushRoute
  '/_admin/admin/referral-config': typeof AdminAdminReferralConfigRoute
  '/_admin/admin/results': typeof AdminAdminResultsRoute
  '/_admin/admin/security': typeof AdminAdminSecurityRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/shop': typeof AdminAdminShopRoute
  '/_admin/admin/smtp': typeof AdminAdminSmtpRoute
  '/_admin/admin/support': typeof AdminAdminSupportRoute
  '/_admin/admin/templates': typeof AdminAdminTemplatesRoute
  '/_admin/admin/two-factor': typeof AdminAdminTwoFactorRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/withdraw-config': typeof AdminAdminWithdrawConfigRoute
  '/_admin/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/_authenticated/dashboard/blocks': typeof AuthenticatedDashboardBlocksRoute
  '/_authenticated/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/_authenticated/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/_authenticated/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/_authenticated/dashboard/statistics': typeof AuthenticatedDashboardStatisticsRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/dashboard/vault': typeof AuthenticatedDashboardVaultRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/feed/new': typeof AuthenticatedFeedNewRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/_authenticated/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
  '/_authenticated/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/_authenticated/dashboard/story/new': typeof AuthenticatedDashboardStoryNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apk'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/leaderboard'
    | '/matches'
    | '/news'
    | '/premium'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/dashboard'
    | '/auth/callback'
    | '/email/verify'
    | '/p/$slug'
    | '/post/$postId'
    | '/u/$username'
    | '/admin/account-deletions'
    | '/admin/apk'
    | '/admin/backups'
    | '/admin/balances'
    | '/admin/business-wallets'
    | '/admin/channels'
    | '/admin/coin-rates'
    | '/admin/deposits'
    | '/admin/email-setup'
    | '/admin/feed'
    | '/admin/games'
    | '/admin/login-history'
    | '/admin/matches'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/pages'
    | '/admin/participants'
    | '/admin/premium'
    | '/admin/push'
    | '/admin/referral-config'
    | '/admin/results'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/smtp'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/two-factor'
    | '/admin/users'
    | '/admin/withdraw-config'
    | '/admin/withdrawals'
    | '/dashboard/blocks'
    | '/dashboard/feed'
    | '/dashboard/matches'
    | '/dashboard/messages'
    | '/dashboard/my-matches'
    | '/dashboard/notifications'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/shop'
    | '/dashboard/statistics'
    | '/dashboard/support'
    | '/dashboard/vault'
    | '/dashboard/wallet'
    | '/feed/new'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/feed/$postId'
    | '/dashboard/matches/$matchId'
    | '/dashboard/messages/$threadId'
    | '/dashboard/story/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apk'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/leaderboard'
    | '/matches'
    | '/news'
    | '/premium'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/auth/callback'
    | '/email/verify'
    | '/p/$slug'
    | '/post/$postId'
    | '/u/$username'
    | '/admin/account-deletions'
    | '/admin/apk'
    | '/admin/backups'
    | '/admin/balances'
    | '/admin/business-wallets'
    | '/admin/channels'
    | '/admin/coin-rates'
    | '/admin/deposits'
    | '/admin/email-setup'
    | '/admin/feed'
    | '/admin/games'
    | '/admin/login-history'
    | '/admin/matches'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/pages'
    | '/admin/participants'
    | '/admin/premium'
    | '/admin/push'
    | '/admin/referral-config'
    | '/admin/results'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/smtp'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/two-factor'
    | '/admin/users'
    | '/admin/withdraw-config'
    | '/admin/withdrawals'
    | '/dashboard/blocks'
    | '/dashboard/feed'
    | '/dashboard/matches'
    | '/dashboard/messages'
    | '/dashboard/my-matches'
    | '/dashboard/notifications'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/shop'
    | '/dashboard/statistics'
    | '/dashboard/support'
    | '/dashboard/vault'
    | '/dashboard/wallet'
    | '/feed/new'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/admin'
    | '/dashboard'
    | '/dashboard/feed/$postId'
    | '/dashboard/matches/$matchId'
    | '/dashboard/messages/$threadId'
    | '/dashboard/story/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/apk'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/leaderboard'
    | '/matches'
    | '/news'
    | '/premium'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/email/verify'
    | '/p/$slug'
    | '/post/$postId'
    | '/u/$username'
    | '/_admin/admin/account-deletions'
    | '/_admin/admin/apk'
    | '/_admin/admin/backups'
    | '/_admin/admin/balances'
    | '/_admin/admin/business-wallets'
    | '/_admin/admin/channels'
    | '/_admin/admin/coin-rates'
    | '/_admin/admin/deposits'
    | '/_admin/admin/email-setup'
    | '/_admin/admin/feed'
    | '/_admin/admin/games'
    | '/_admin/admin/login-history'
    | '/_admin/admin/matches'
    | '/_admin/admin/notifications'
    | '/_admin/admin/online-users'
    | '/_admin/admin/pages'
    | '/_admin/admin/participants'
    | '/_admin/admin/premium'
    | '/_admin/admin/push'
    | '/_admin/admin/referral-config'
    | '/_admin/admin/results'
    | '/_admin/admin/security'
    | '/_admin/admin/settings'
    | '/_admin/admin/shop'
    | '/_admin/admin/smtp'
    | '/_admin/admin/support'
    | '/_admin/admin/templates'
    | '/_admin/admin/two-factor'
    | '/_admin/admin/users'
    | '/_admin/admin/withdraw-config'
    | '/_admin/admin/withdrawals'
    | '/_authenticated/dashboard/blocks'
    | '/_authenticated/dashboard/feed'
    | '/_authenticated/dashboard/matches'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/my-matches'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/premium'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/referrals'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/shop'
    | '/_authenticated/dashboard/statistics'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/dashboard/vault'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/feed/new'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/feed/$postId'
    | '/_authenticated/dashboard/matches/$matchId'
    | '/_authenticated/dashboard/messages/$threadId'
    | '/_authenticated/dashboard/story/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApkRoute: typeof ApkRoute
  AuthRoute: typeof AuthRouteWithChildren
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesRoute: typeof MatchesRoute
  NewsRoute: typeof NewsRoute
  PremiumRoute: typeof PremiumRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  EmailVerifyRoute: typeof EmailVerifyRoute
  PSlugRoute: typeof PSlugRoute
  PostPostIdRoute: typeof PostPostIdRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk': {
      id: '/apk'
      path: '/apk'
      fullPath: '/apk'
      preLoaderRoute: typeof ApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify': {
      id: '/email/verify'
      path: '/email/verify'
      fullPath: '/email/verify'
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/u/$username/following': {
      id: '/u/$username/following'
      path: '/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof UUsernameFollowingRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/followers': {
      id: '/u/$username/followers'
      path: '/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof UUsernameFollowersRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/_authenticated/feed/new': {
      id: '/_authenticated/feed/new'
      path: '/feed/new'
      fullPath: '/feed/new'
      preLoaderRoute: typeof AuthenticatedFeedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vault': {
      id: '/_authenticated/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof AuthenticatedDashboardVaultRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/statistics': {
      id: '/_authenticated/dashboard/statistics'
      path: '/statistics'
      fullPath: '/dashboard/statistics'
      preLoaderRoute: typeof AuthenticatedDashboardStatisticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shop': {
      id: '/_authenticated/dashboard/shop'
      path: '/shop'
      fullPath: '/dashboard/shop'
      preLoaderRoute: typeof AuthenticatedDashboardShopRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/referrals': {
      id: '/_authenticated/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/premium': {
      id: '/_authenticated/dashboard/premium'
      path: '/premium'
      fullPath: '/dashboard/premium'
      preLoaderRoute: typeof AuthenticatedDashboardPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-matches': {
      id: '/_authenticated/dashboard/my-matches'
      path: '/my-matches'
      fullPath: '/dashboard/my-matches'
      preLoaderRoute: typeof AuthenticatedDashboardMyMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matches': {
      id: '/_authenticated/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof AuthenticatedDashboardMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/feed': {
      id: '/_authenticated/dashboard/feed'
      path: '/feed'
      fullPath: '/dashboard/feed'
      preLoaderRoute: typeof AuthenticatedDashboardFeedRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/blocks': {
      id: '/_authenticated/dashboard/blocks'
      path: '/blocks'
      fullPath: '/dashboard/blocks'
      preLoaderRoute: typeof AuthenticatedDashboardBlocksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/withdrawals': {
      id: '/_admin/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminAdminWithdrawalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/withdraw-config': {
      id: '/_admin/admin/withdraw-config'
      path: '/admin/withdraw-config'
      fullPath: '/admin/withdraw-config'
      preLoaderRoute: typeof AdminAdminWithdrawConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/two-factor': {
      id: '/_admin/admin/two-factor'
      path: '/admin/two-factor'
      fullPath: '/admin/two-factor'
      preLoaderRoute: typeof AdminAdminTwoFactorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/templates': {
      id: '/_admin/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminAdminTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/support': {
      id: '/_admin/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/smtp': {
      id: '/_admin/admin/smtp'
      path: '/admin/smtp'
      fullPath: '/admin/smtp'
      preLoaderRoute: typeof AdminAdminSmtpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/shop': {
      id: '/_admin/admin/shop'
      path: '/admin/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminAdminShopRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/security': {
      id: '/_admin/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/results': {
      id: '/_admin/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminAdminResultsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/referral-config': {
      id: '/_admin/admin/referral-config'
      path: '/admin/referral-config'
      fullPath: '/admin/referral-config'
      preLoaderRoute: typeof AdminAdminReferralConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/push': {
      id: '/_admin/admin/push'
      path: '/admin/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminAdminPushRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/premium': {
      id: '/_admin/admin/premium'
      path: '/admin/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminAdminPremiumRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/participants': {
      id: '/_admin/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminAdminParticipantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pages': {
      id: '/_admin/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminAdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/online-users': {
      id: '/_admin/admin/online-users'
      path: '/admin/online-users'
      fullPath: '/admin/online-users'
      preLoaderRoute: typeof AdminAdminOnlineUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/matches': {
      id: '/_admin/admin/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminAdminMatchesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/login-history': {
      id: '/_admin/admin/login-history'
      path: '/admin/login-history'
      fullPath: '/admin/login-history'
      preLoaderRoute: typeof AdminAdminLoginHistoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/games': {
      id: '/_admin/admin/games'
      path: '/admin/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminAdminGamesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/feed': {
      id: '/_admin/admin/feed'
      path: '/admin/feed'
      fullPath: '/admin/feed'
      preLoaderRoute: typeof AdminAdminFeedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/email-setup': {
      id: '/_admin/admin/email-setup'
      path: '/admin/email-setup'
      fullPath: '/admin/email-setup'
      preLoaderRoute: typeof AdminAdminEmailSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/deposits': {
      id: '/_admin/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminAdminDepositsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/coin-rates': {
      id: '/_admin/admin/coin-rates'
      path: '/admin/coin-rates'
      fullPath: '/admin/coin-rates'
      preLoaderRoute: typeof AdminAdminCoinRatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/channels': {
      id: '/_admin/admin/channels'
      path: '/admin/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminAdminChannelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/business-wallets': {
      id: '/_admin/admin/business-wallets'
      path: '/admin/business-wallets'
      fullPath: '/admin/business-wallets'
      preLoaderRoute: typeof AdminAdminBusinessWalletsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/balances': {
      id: '/_admin/admin/balances'
      path: '/admin/balances'
      fullPath: '/admin/balances'
      preLoaderRoute: typeof AdminAdminBalancesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/backups': {
      id: '/_admin/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminAdminBackupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/apk': {
      id: '/_admin/admin/apk'
      path: '/admin/apk'
      fullPath: '/admin/apk'
      preLoaderRoute: typeof AdminAdminApkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/account-deletions': {
      id: '/_admin/admin/account-deletions'
      path: '/admin/account-deletions'
      fullPath: '/admin/account-deletions'
      preLoaderRoute: typeof AdminAdminAccountDeletionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard/story/new': {
      id: '/_authenticated/dashboard/story/new'
      path: '/story/new'
      fullPath: '/dashboard/story/new'
      preLoaderRoute: typeof AuthenticatedDashboardStoryNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages/$threadId': {
      id: '/_authenticated/dashboard/messages/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMessagesRoute
    }
    '/_authenticated/dashboard/matches/$matchId': {
      id: '/_authenticated/dashboard/matches/$matchId'
      path: '/$matchId'
      fullPath: '/dashboard/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedDashboardMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMatchesRoute
    }
    '/_authenticated/dashboard/feed/$postId': {
      id: '/_authenticated/dashboard/feed/$postId'
      path: '/$postId'
      fullPath: '/dashboard/feed/$postId'
      preLoaderRoute: typeof AuthenticatedDashboardFeedPostIdRouteImport
      parentRoute: typeof AuthenticatedDashboardFeedRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminAccountDeletionsRoute: typeof AdminAdminAccountDeletionsRoute
  AdminAdminApkRoute: typeof AdminAdminApkRoute
  AdminAdminBackupsRoute: typeof AdminAdminBackupsRoute
  AdminAdminBalancesRoute: typeof AdminAdminBalancesRoute
  AdminAdminBusinessWalletsRoute: typeof AdminAdminBusinessWalletsRoute
  AdminAdminChannelsRoute: typeof AdminAdminChannelsRoute
  AdminAdminCoinRatesRoute: typeof AdminAdminCoinRatesRoute
  AdminAdminDepositsRoute: typeof AdminAdminDepositsRoute
  AdminAdminEmailSetupRoute: typeof AdminAdminEmailSetupRoute
  AdminAdminFeedRoute: typeof AdminAdminFeedRoute
  AdminAdminGamesRoute: typeof AdminAdminGamesRoute
  AdminAdminLoginHistoryRoute: typeof AdminAdminLoginHistoryRoute
  AdminAdminMatchesRoute: typeof AdminAdminMatchesRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminOnlineUsersRoute: typeof AdminAdminOnlineUsersRoute
  AdminAdminPagesRoute: typeof AdminAdminPagesRoute
  AdminAdminParticipantsRoute: typeof AdminAdminParticipantsRoute
  AdminAdminPremiumRoute: typeof AdminAdminPremiumRoute
  AdminAdminPushRoute: typeof AdminAdminPushRoute
  AdminAdminReferralConfigRoute: typeof AdminAdminReferralConfigRoute
  AdminAdminResultsRoute: typeof AdminAdminResultsRoute
  AdminAdminSecurityRoute: typeof AdminAdminSecurityRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminShopRoute: typeof AdminAdminShopRoute
  AdminAdminSmtpRoute: typeof AdminAdminSmtpRoute
  AdminAdminSupportRoute: typeof AdminAdminSupportRoute
  AdminAdminTemplatesRoute: typeof AdminAdminTemplatesRoute
  AdminAdminTwoFactorRoute: typeof AdminAdminTwoFactorRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminWithdrawConfigRoute: typeof AdminAdminWithdrawConfigRoute
  AdminAdminWithdrawalsRoute: typeof AdminAdminWithdrawalsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminAccountDeletionsRoute: AdminAdminAccountDeletionsRoute,
  AdminAdminApkRoute: AdminAdminApkRoute,
  AdminAdminBackupsRoute: AdminAdminBackupsRoute,
  AdminAdminBalancesRoute: AdminAdminBalancesRoute,
  AdminAdminBusinessWalletsRoute: AdminAdminBusinessWalletsRoute,
  AdminAdminChannelsRoute: AdminAdminChannelsRoute,
  AdminAdminCoinRatesRoute: AdminAdminCoinRatesRoute,
  AdminAdminDepositsRoute: AdminAdminDepositsRoute,
  AdminAdminEmailSetupRoute: AdminAdminEmailSetupRoute,
  AdminAdminFeedRoute: AdminAdminFeedRoute,
  AdminAdminGamesRoute: AdminAdminGamesRoute,
  AdminAdminLoginHistoryRoute: AdminAdminLoginHistoryRoute,
  AdminAdminMatchesRoute: AdminAdminMatchesRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminOnlineUsersRoute: AdminAdminOnlineUsersRoute,
  AdminAdminPagesRoute: AdminAdminPagesRoute,
  AdminAdminParticipantsRoute: AdminAdminParticipantsRoute,
  AdminAdminPremiumRoute: AdminAdminPremiumRoute,
  AdminAdminPushRoute: AdminAdminPushRoute,
  AdminAdminReferralConfigRoute: AdminAdminReferralConfigRoute,
  AdminAdminResultsRoute: AdminAdminResultsRoute,
  AdminAdminSecurityRoute: AdminAdminSecurityRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminShopRoute: AdminAdminShopRoute,
  AdminAdminSmtpRoute: AdminAdminSmtpRoute,
  AdminAdminSupportRoute: AdminAdminSupportRoute,
  AdminAdminTemplatesRoute: AdminAdminTemplatesRoute,
  AdminAdminTwoFactorRoute: AdminAdminTwoFactorRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminWithdrawConfigRoute: AdminAdminWithdrawConfigRoute,
  AdminAdminWithdrawalsRoute: AdminAdminWithdrawalsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedDashboardFeedRouteChildren {
  AuthenticatedDashboardFeedPostIdRoute: typeof AuthenticatedDashboardFeedPostIdRoute
}

const AuthenticatedDashboardFeedRouteChildren: AuthenticatedDashboardFeedRouteChildren =
  {
    AuthenticatedDashboardFeedPostIdRoute:
      AuthenticatedDashboardFeedPostIdRoute,
  }

const AuthenticatedDashboardFeedRouteWithChildren =
  AuthenticatedDashboardFeedRoute._addFileChildren(
    AuthenticatedDashboardFeedRouteChildren,
  )

interface AuthenticatedDashboardMatchesRouteChildren {
  AuthenticatedDashboardMatchesMatchIdRoute: typeof AuthenticatedDashboardMatchesMatchIdRoute
}

const AuthenticatedDashboardMatchesRouteChildren: AuthenticatedDashboardMatchesRouteChildren =
  {
    AuthenticatedDashboardMatchesMatchIdRoute:
      AuthenticatedDashboardMatchesMatchIdRoute,
  }

const AuthenticatedDashboardMatchesRouteWithChildren =
  AuthenticatedDashboardMatchesRoute._addFileChildren(
    AuthenticatedDashboardMatchesRouteChildren,
  )

interface AuthenticatedDashboardMessagesRouteChildren {
  AuthenticatedDashboardMessagesThreadIdRoute: typeof AuthenticatedDashboardMessagesThreadIdRoute
}

const AuthenticatedDashboardMessagesRouteChildren: AuthenticatedDashboardMessagesRouteChildren =
  {
    AuthenticatedDashboardMessagesThreadIdRoute:
      AuthenticatedDashboardMessagesThreadIdRoute,
  }

const AuthenticatedDashboardMessagesRouteWithChildren =
  AuthenticatedDashboardMessagesRoute._addFileChildren(
    AuthenticatedDashboardMessagesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBlocksRoute: typeof AuthenticatedDashboardBlocksRoute
  AuthenticatedDashboardFeedRoute: typeof AuthenticatedDashboardFeedRouteWithChildren
  AuthenticatedDashboardMatchesRoute: typeof AuthenticatedDashboardMatchesRouteWithChildren
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRouteWithChildren
  AuthenticatedDashboardMyMatchesRoute: typeof AuthenticatedDashboardMyMatchesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPremiumRoute: typeof AuthenticatedDashboardPremiumRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardReferralsRoute: typeof AuthenticatedDashboardReferralsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardShopRoute: typeof AuthenticatedDashboardShopRoute
  AuthenticatedDashboardStatisticsRoute: typeof AuthenticatedDashboardStatisticsRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
  AuthenticatedDashboardVaultRoute: typeof AuthenticatedDashboardVaultRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardStoryNewRoute: typeof AuthenticatedDashboardStoryNewRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBlocksRoute: AuthenticatedDashboardBlocksRoute,
    AuthenticatedDashboardFeedRoute:
      AuthenticatedDashboardFeedRouteWithChildren,
    AuthenticatedDashboardMatchesRoute:
      AuthenticatedDashboardMatchesRouteWithChildren,
    AuthenticatedDashboardMessagesRoute:
      AuthenticatedDashboardMessagesRouteWithChildren,
    AuthenticatedDashboardMyMatchesRoute: AuthenticatedDashboardMyMatchesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPremiumRoute: AuthenticatedDashboardPremiumRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardReferralsRoute: AuthenticatedDashboardReferralsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardShopRoute: AuthenticatedDashboardShopRoute,
    AuthenticatedDashboardStatisticsRoute:
      AuthenticatedDashboardStatisticsRoute,
    AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
    AuthenticatedDashboardVaultRoute: AuthenticatedDashboardVaultRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardStoryNewRoute: AuthenticatedDashboardStoryNewRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedFeedNewRoute: typeof AuthenticatedFeedNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedFeedNewRoute: AuthenticatedFeedNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UUsernameRouteChildren {
  UUsernameFollowersRoute: typeof UUsernameFollowersRoute
  UUsernameFollowingRoute: typeof UUsernameFollowingRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameFollowersRoute: UUsernameFollowersRoute,
  UUsernameFollowingRoute: UUsernameFollowingRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApkRoute: ApkRoute,
  AuthRoute: AuthRouteWithChildren,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesRoute: MatchesRoute,
  NewsRoute: NewsRoute,
  PremiumRoute: PremiumRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  EmailVerifyRoute: EmailVerifyRoute,
  PSlugRoute: PSlugRoute,
  PostPostIdRoute: PostPostIdRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
