/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailVerifyRouteImport } from './routes/email.verify'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard.wallet'
import { Route as AuthenticatedDashboardShopRouteImport } from './routes/_authenticated/dashboard.shop'
import { Route as AuthenticatedDashboardReferralsRouteImport } from './routes/_authenticated/dashboard.referrals'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPremiumRouteImport } from './routes/_authenticated/dashboard.premium'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMyMatchesRouteImport } from './routes/_authenticated/dashboard.my-matches'
import { Route as AuthenticatedDashboardMatchesRouteImport } from './routes/_authenticated/dashboard.matches'
import { Route as AuthenticatedDashboardFeedRouteImport } from './routes/_authenticated/dashboard.feed'
import { Route as AuthenticatedDashboardMatchesMatchIdRouteImport } from './routes/_authenticated/dashboard.matches.$matchId'
import { Route as AuthenticatedDashboardFeedPostIdRouteImport } from './routes/_authenticated/dashboard.feed.$postId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShopRoute =
  AuthenticatedDashboardShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReferralsRoute =
  AuthenticatedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPremiumRoute =
  AuthenticatedDashboardPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyMatchesRoute =
  AuthenticatedDashboardMyMatchesRouteImport.update({
    id: '/my-matches',
    path: '/my-matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatchesRoute =
  AuthenticatedDashboardMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFeedRoute =
  AuthenticatedDashboardFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatchesMatchIdRoute =
  AuthenticatedDashboardMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedDashboardMatchesRoute,
  } as any)
const AuthenticatedDashboardFeedPostIdRoute =
  AuthenticatedDashboardFeedPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthenticatedDashboardFeedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/email/verify': typeof EmailVerifyRoute
  '/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/email/verify': typeof EmailVerifyRoute
  '/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/email/verify': typeof EmailVerifyRoute
  '/_authenticated/dashboard/feed': typeof AuthenticatedDashboardFeedRouteWithChildren
  '/_authenticated/dashboard/matches': typeof AuthenticatedDashboardMatchesRouteWithChildren
  '/_authenticated/dashboard/my-matches': typeof AuthenticatedDashboardMyMatchesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/_authenticated/dashboard/shop': typeof AuthenticatedDashboardShopRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/dashboard/feed/$postId': typeof AuthenticatedDashboardFeedPostIdRoute
  '/_authenticated/dashboard/matches/$matchId': typeof AuthenticatedDashboardMatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/email/verify'
    | '/dashboard/feed'
    | '/dashboard/matches'
    | '/dashboard/my-matches'
    | '/dashboard/notifications'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/shop'
    | '/dashboard/wallet'
    | '/dashboard/feed/$postId'
    | '/dashboard/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/email/verify'
    | '/dashboard/feed'
    | '/dashboard/matches'
    | '/dashboard/my-matches'
    | '/dashboard/notifications'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/shop'
    | '/dashboard/wallet'
    | '/dashboard/feed/$postId'
    | '/dashboard/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/email/verify'
    | '/_authenticated/dashboard/feed'
    | '/_authenticated/dashboard/matches'
    | '/_authenticated/dashboard/my-matches'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/premium'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/referrals'
    | '/_authenticated/dashboard/shop'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/dashboard/feed/$postId'
    | '/_authenticated/dashboard/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EmailVerifyRoute: typeof EmailVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify': {
      id: '/email/verify'
      path: '/email/verify'
      fullPath: '/email/verify'
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shop': {
      id: '/_authenticated/dashboard/shop'
      path: '/shop'
      fullPath: '/dashboard/shop'
      preLoaderRoute: typeof AuthenticatedDashboardShopRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/referrals': {
      id: '/_authenticated/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/premium': {
      id: '/_authenticated/dashboard/premium'
      path: '/premium'
      fullPath: '/dashboard/premium'
      preLoaderRoute: typeof AuthenticatedDashboardPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-matches': {
      id: '/_authenticated/dashboard/my-matches'
      path: '/my-matches'
      fullPath: '/dashboard/my-matches'
      preLoaderRoute: typeof AuthenticatedDashboardMyMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matches': {
      id: '/_authenticated/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof AuthenticatedDashboardMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/feed': {
      id: '/_authenticated/dashboard/feed'
      path: '/feed'
      fullPath: '/dashboard/feed'
      preLoaderRoute: typeof AuthenticatedDashboardFeedRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matches/$matchId': {
      id: '/_authenticated/dashboard/matches/$matchId'
      path: '/$matchId'
      fullPath: '/dashboard/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedDashboardMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMatchesRoute
    }
    '/_authenticated/dashboard/feed/$postId': {
      id: '/_authenticated/dashboard/feed/$postId'
      path: '/$postId'
      fullPath: '/dashboard/feed/$postId'
      preLoaderRoute: typeof AuthenticatedDashboardFeedPostIdRouteImport
      parentRoute: typeof AuthenticatedDashboardFeedRoute
    }
  }
}

interface AuthenticatedDashboardFeedRouteChildren {
  AuthenticatedDashboardFeedPostIdRoute: typeof AuthenticatedDashboardFeedPostIdRoute
}

const AuthenticatedDashboardFeedRouteChildren: AuthenticatedDashboardFeedRouteChildren =
  {
    AuthenticatedDashboardFeedPostIdRoute:
      AuthenticatedDashboardFeedPostIdRoute,
  }

const AuthenticatedDashboardFeedRouteWithChildren =
  AuthenticatedDashboardFeedRoute._addFileChildren(
    AuthenticatedDashboardFeedRouteChildren,
  )

interface AuthenticatedDashboardMatchesRouteChildren {
  AuthenticatedDashboardMatchesMatchIdRoute: typeof AuthenticatedDashboardMatchesMatchIdRoute
}

const AuthenticatedDashboardMatchesRouteChildren: AuthenticatedDashboardMatchesRouteChildren =
  {
    AuthenticatedDashboardMatchesMatchIdRoute:
      AuthenticatedDashboardMatchesMatchIdRoute,
  }

const AuthenticatedDashboardMatchesRouteWithChildren =
  AuthenticatedDashboardMatchesRoute._addFileChildren(
    AuthenticatedDashboardMatchesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardFeedRoute: typeof AuthenticatedDashboardFeedRouteWithChildren
  AuthenticatedDashboardMatchesRoute: typeof AuthenticatedDashboardMatchesRouteWithChildren
  AuthenticatedDashboardMyMatchesRoute: typeof AuthenticatedDashboardMyMatchesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPremiumRoute: typeof AuthenticatedDashboardPremiumRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardReferralsRoute: typeof AuthenticatedDashboardReferralsRoute
  AuthenticatedDashboardShopRoute: typeof AuthenticatedDashboardShopRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardFeedRoute:
      AuthenticatedDashboardFeedRouteWithChildren,
    AuthenticatedDashboardMatchesRoute:
      AuthenticatedDashboardMatchesRouteWithChildren,
    AuthenticatedDashboardMyMatchesRoute: AuthenticatedDashboardMyMatchesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPremiumRoute: AuthenticatedDashboardPremiumRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardReferralsRoute: AuthenticatedDashboardReferralsRoute,
    AuthenticatedDashboardShopRoute: AuthenticatedDashboardShopRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EmailVerifyRoute: EmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
