
REVOKE EXECUTE ON FUNCTION public.submit_deposit(BIGINT, BIGINT, NUMERIC, TEXT, NUMERIC, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.submit_withdrawal(NUMERIC, BIGINT, TEXT, TEXT) FROM PUBLIC, anon;
